openapi: 3.0.3

info:
  title: API de Productos
  description: API desarrollada en Dart para consultar productos.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local

tags:
  - name: Productos
    description: Operaciones relacionadas con productos

paths:
  /api/productos:
    get:
      summary: Obtener todos los productos
      description: Obtiene todos los productos registrados en la base de datos.
      tags:
        - Productos

      responses:
        '200':
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1

                    nombre:
                      type: string
                      example: Laptop Lenovo

                    precio:
                      type: number
                      format: double
                      example: 3500.00